spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizza
    username: pizza
    password: pizza
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: pizza.zickner.ordersystem.web.configuration.CompatibilityNamingStrategy
security:
  basic:
    path: /api